//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLicensing.Powershell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoreLicensing.Powershell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound to MSA: {0}.
        /// </summary>
        internal static string BoundToMSA {
            get {
                return ResourceManager.GetString("BoundToMSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound to SID: {0}.
        /// </summary>
        internal static string BoundToSID {
            get {
                return ResourceManager.GetString("BoundToSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: {0}.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentId: {0}.
        /// </summary>
        internal static string ContentId {
            get {
                return ResourceManager.GetString("ContentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration: {0}.
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command failed with exception: {0}.
        /// </summary>
        internal static string GeneralFailure {
            get {
                return ResourceManager.GetString("GeneralFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid: 0x{0:X8}.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued: {0}.
        /// </summary>
        internal static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leases.
        /// </summary>
        internal static string Leases {
            get {
                return ResourceManager.GetString("Leases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id: {0}.
        /// </summary>
        internal static string LicenseId {
            get {
                return ResourceManager.GetString("LicenseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no key or lease installed for {0}.
        /// </summary>
        internal static string LicenseNotFound {
            get {
                return ResourceManager.GetString("LicenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string NoExpiration {
            get {
                return ResourceManager.GetString("NoExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string NoIssueDate {
            get {
                return ResourceManager.GetString("NoIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.  You need to run this command as admin..
        /// </summary>
        internal static string NotRunningAsAdmin {
            get {
                return ResourceManager.GetString("NotRunningAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Family Name: {0}.
        /// </summary>
        internal static string PackageFamilyName {
            get {
                return ResourceManager.GetString("PackageFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Family Names: {0}.
        /// </summary>
        internal static string PackageFamilyNames {
            get {
                return ResourceManager.GetString("PackageFamilyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires lease: {0}.
        /// </summary>
        internal static string RequiresLease {
            get {
                return ResourceManager.GetString("RequiresLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command completed successfully..
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command completed successfully but requires a reboot to take effect..
        /// </summary>
        internal static string SuccessWithRebootMessage {
            get {
                return ResourceManager.GetString("SuccessWithRebootMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get key or lease for {0}, exception {1}..
        /// </summary>
        internal static string UnableToGetLicense {
            get {
                return ResourceManager.GetString("UnableToGetLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity: {0}.
        /// </summary>
        internal static string Validity {
            get {
                return ResourceManager.GetString("Validity", resourceCulture);
            }
        }
    }
}
